export default function TermsPage(): React.JSX.Element {
  return (
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "48px 24px", fontFamily: "inherit" }}>
      <h1 style={{ fontSize: 28, fontWeight: 700, letterSpacing: "-0.02em", margin: "0 0 8px" }}>
        Terms of Service
      </h1>
      <p style={{ fontSize: 13, color: "#6b7280", margin: "0 0 40px" }}>
        Last updated: April 2026
      </p>

      <Section title="What this service is">
        <p>
          This is an AI-assisted job application tool. It helps you build a candidate profile from
          your own documents and generates tailored CVs and cover letters for specific roles you
          are applying to.
        </p>
        <p>
          The service is currently in beta. Features may change, and we appreciate your patience
          while we improve things.
        </p>
      </Section>

      <Section title="What the service does not do">
        <p>
          This service does not submit applications on your behalf. It does not contact employers.
          It does not guarantee interviews, offers, or any particular outcome. All generated
          documents are drafts — they are starting points for your review, not finished submissions.
        </p>
      </Section>

      <Section title="Your responsibility for the content">
        <p>
          Everything the service generates is based on information you provide. You are responsible
          for reviewing all generated content before using it in a real application.
        </p>
        <p>
          You must not use the service to create documents containing false information, fabricated
          experience, or misleading claims. The service is designed to help you present your real
          experience more effectively — not to invent things that are not true.
        </p>
        <p>
          By using this service, you confirm that the documents and information you upload belong
          to you or that you have the right to use them.
        </p>
      </Section>

      <Section title="Generated documents are drafts">
        <p>
          CV and cover letter outputs from this service are AI-generated drafts. They may contain
          errors, awkward phrasing, or inaccuracies. You should read every word before submitting
          anything to an employer.
        </p>
        <p>
          We strongly recommend treating the output as a starting point, not a finished document.
          Your judgment, your edits, and your authentic voice are what make an application
          compelling — the service is here to help you get there faster, not to replace your
          involvement.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You are responsible for keeping your login credentials secure. Do not share your account
          with others. If you believe your account has been compromised, sign out and contact us.
        </p>
        <p>
          You can delete your account at any time from the Settings page. This permanently removes
          all your data.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>
          You may use this service for personal job searching and application purposes. You may not
          use it to create documents for other people without their knowledge, to conduct bulk or
          automated application campaigns, or for any purpose that violates applicable law.
        </p>
      </Section>

      <Section title="Availability and changes">
        <p>
          We aim to keep the service available but cannot guarantee uninterrupted access,
          particularly during the beta period. We may update, change, or discontinue features with
          notice where practical.
        </p>
        <p>
          We will update these terms when something material changes and will note the update date
          at the top of this page.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the extent permitted by law, this service is provided as-is. We are not liable for
          outcomes of job applications made using documents generated by this service, for errors
          or inaccuracies in generated content, or for any loss arising from reliance on the
          service without your own review and judgment.
        </p>
        <p>
          Nothing in these terms limits liability for fraud, gross negligence, or any liability
          that cannot be excluded by law.
        </p>
      </Section>

      <Section title="Governing law">
        <p>
          These terms are governed by German law. Any disputes will be subject to the jurisdiction
          of the courts of Germany, unless mandatory consumer protection laws in your country of
          residence apply.
        </p>
      </Section>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2
        style={{
          fontSize: 17,
          fontWeight: 700,
          color: "#111827",
          margin: "0 0 12px",
          letterSpacing: "-0.01em",
        }}
      >
        {title}
      </h2>
      <div
        style={{
          fontSize: 14,
          lineHeight: 1.8,
          color: "#374151",
        }}
      >
        {children}
      </div>
    </section>
  );
}
